// models/Terminal.js
import mongoose from "mongoose";
import crypto from "crypto";

const terminalSchema = new mongoose.Schema(
  {
    outletId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Outlet",
      required: true,
      index: true,
    },

    code: { type: String, required: true, trim: true, index: true },
    description: { type: String, trim: true },

    // Permanent launcher identity generated by the Electron app.
    // This remains unchanged across launcher updates.
    machineId: {
      type: String,
      trim: true,
      unique: true,
      sparse: true,
      index: true,
    },

    // For launcher-paired terminals, deviceKey should be the same as machineId.
    // Kept for backward compatibility with your current heartbeat and WS flow.
    deviceKey: {
      type: String,
      required: true,
      trim: true,
      unique: true,
      index: true,
    },

    hostname: { type: String, trim: true, default: "" },
    launcherVersion: { type: String, trim: true, default: "" },
    pairedAt: { type: Date, default: null },
    lastLauncherOpenAt: { type: Date, default: null },
    lastLauncherCloseAt: { type: Date, default: null },

    isLocked: { type: Boolean, default: false },
    isGameDisabled: { type: Boolean, default: false },
    isLaunchedGame: { type: Boolean, default: false },
    active: { type: Boolean, default: true },
    isOnline: { type: Boolean, default: false },
    lastSeenAt: { type: Date, default: null },
    lastStatus: {
      isPlaying: { type: Boolean, default: false },
      videoUrl: { type: String, default: "" },
      positionSec: { type: Number, default: 0 },
      hasError: { type: Boolean, default: false },
      displayId: { type: String, default: null },
      mode: { type: String, default: "promo" },
      updatedAt: { type: Date, default: null },
    },
  },
  { timestamps: true },
);

terminalSchema.index({ outletId: 1, code: 1 }, { unique: true });

terminalSchema.statics.generateDeviceKey = function (outletCode, terminalCode) {
  const uniqueString = `${outletCode}-${terminalCode}-${Date.now()}-${Math.random()
    .toString(36)
    .substr(2, 9)}`;
  const hash = crypto.createHash("sha256");
  hash.update(uniqueString);
  return hash.digest("hex").substring(0, 32);
};

terminalSchema.statics.getNextTerminalNumber = async function (outletId) {
  const terminals = await this.find({ outletId }).select("code").lean();
  let nextNumber = 1;

  for (const terminal of terminals) {
    const match = String(terminal.code || "").match(/^T(\d+)$/i);
    if (!match) continue;
    const number = Number(match[1]);
    if (Number.isFinite(number) && number >= nextNumber) {
      nextNumber = number + 1;
    }
  }

  return nextNumber;
};

terminalSchema.statics.getNextTerminalCode = async function (outletId) {
  const nextNumber = await this.getNextTerminalNumber(outletId);
  return `T${nextNumber}`;
};

terminalSchema.statics.generateTerminalCodes = async function (outletId, count) {
  const startNumber = await this.getNextTerminalNumber(outletId);
  const codes = [];

  for (let i = 0; i < count; i++) {
    codes.push(`T${startNumber + i}`);
  }

  return codes;
};

export default mongoose.model("Terminal", terminalSchema);
